---
- hosts: all
  become: yes
  tasks:
  - name: create ansible nodes
    ec2:
      key_name: Mumbai
      group: ansible
      instance_type: t2.micro
      image: ami-0882375271a4bdb70
      wait: yes
      region: ap-south-1
      count: 2
      instance_tags:
         name: ansible_node
      vpc_subnet_id: subnet-53686d3b
      assign_public_ip: yes

