---
  - name: copy tomcat manager xml file into node side
    template: 
       src: templates/tomcatmanagerxmlfile.j2
       dest: /opt/tomcat/webapps/manager/META-INF/context.xml


  - name: copy tomcat host manager xmlfile into my node side 
    template:
        src: templates/tomcathostmanagerxmlfile.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
